excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

trailing_comma:
    mandatory_comma: true

identifier_name:
    min_length: 2
    max_length: 40

type_name:
    min_length: 2
    max_length: 40

nesting:
    type_level: 10

disabled_rules:
    closure_parameter_position
